business_time:
  # 업무 시작/종료 시간 설정
  beginning_of_workday: 9:00 am
  end_of_workday: 6:00 pm
  
  # 공휴일 설정 (한국 공휴일 2025년)
  holidays:
    - January 1st, 2025    # 신정
    - January 28th, 2025   # 설날 연휴
    - January 29th, 2025
    - January 30th, 2025
    - March 1st, 2025      # 삼일절
    - May 5th, 2025        # 어린이날
    - May 6th, 2025        # 부처님오신날
    - June 6th, 2025       # 현충일
    - August 15th, 2025    # 광복절
    - October 6th, 2025    # 추석 연휴
    - October 7th, 2025
    - October 8th, 2025
    - October 3rd, 2025    # 개천절
    - October 9th, 2025    # 한글날
    - December 25th, 2025  # 크리스마스