development:
  # Configure available database clients. (required)
  clients:
    # Defines the default client. (required)
    default:
      # Database for execution data (Milestones, Sprints, Tasks)
      # Admin 계정 사용 (컬렉션 생성 권한 필요)
      uri: mongodb://admin:admin123@localhost:27017/creatia_execution_dev?authSource=admin
      
      options:
        # Force direct connection mode (no replica set)
        connect: :direct
        # Write concern
        write_concern:
          w: 1
          j: false
        # Read preference
        read:
          mode: :primary
        # Retry writes
        retry_writes: true
        # Note that all options listed below are Ruby driver client options (the mongo gem).
        # Please refer to the driver documentation of the version of the mongo gem you are using
        # for the most up-to-date list of options.

        # Change the default write concern. (default = { w: 1 })
        # write:
        #   w: 1

        # Change the default read preference. Valid options for mode are: :secondary,
        # :secondary_preferred, :primary, :primary_preferred, :nearest
        # (default: primary)
        # read:
        #   mode: :secondary_preferred
        #   tag_sets:
        #     - use: web

        # The name of the user for authentication.
        # user: 'user'

        # The password of the user for authentication.
        # password: 'password'

        # The user's database roles.
        # roles:
        #   - 'dbOwner'

        # Change the default authentication mechanism. Valid options include:
        # :scram, :scram256, :mongodb_cr, :mongodb_x509, :gssapi, :aws, :plain.
        # MongoDB Server defaults to :scram, which will use "SCRAM-SHA-256" if available,
        # otherwise fallback to "SCRAM-SHA-1" (:scram256 will always use "SCRAM-SHA-256".)
        # This setting is handled by the MongoDB Ruby Driver. Please refer to:
        # https://mongodb.com/docs/ruby-driver/current/reference/authentication/
        # auth_mech: :scram

        # The database or source to authenticate the user against.
        # (default: the database specified above or admin)
        # auth_source: admin

        # Force the driver cluster to behave in a certain manner instead of auto-discovering.
        # Can be one of: :direct, :replica_set, :sharded. Set to :direct
        # when connecting to hidden members of a replica set.
        # connect: :direct

        # Changes the default time in seconds the server monitors refresh their status
        # via hello commands. (default: 10)
        # heartbeat_frequency: 10

        # The time in seconds for selecting servers for a near read preference. (default: 0.015)
        # local_threshold: 0.015

        # The timeout in seconds for selecting a server for an operation. (default: 30)
        server_selection_timeout: 30

        # The maximum number of connections in the connection pool. (default: 5)
        max_pool_size: 10

        # The minimum number of connections in the connection pool. (default: 1)
        min_pool_size: 2

        # The time to wait, in seconds, in the connection pool for a connection
        # to be checked in before timing out. (default: 5)
        # wait_queue_timeout: 5

        # The time to wait to establish a connection before timing out, in seconds.
        # (default: 10)
        connect_timeout: 10

        # How long to wait for a response for each operation sent to the
        # server. This timeout should be set to a value larger than the
        # processing time for the longest operation that will be executed
        # by the application. Note that this is a client-side timeout;
        # the server may continue executing an operation after the client
        # aborts it with the SocketTimeout exception.
        # (default: nil, meaning no timeout)
        socket_timeout: 5

        # The name of the replica set to connect to. Servers provided as seeds that do
        # not belong to this replica set will be ignored.
        # replica_set: name

        # Compressors to use for wire protocol compression. (default is to not use compression)
        # "zstd" requires zstd-ruby gem. "snappy" requires snappy gem.
        # Refer to: https://www.mongodb.com/docs/ruby-driver/current/reference/create-client/#compression
        # compressors: ["zstd", "snappy", "zlib"]

        # The number of times to attempt a read operation before giving up. (default: 1)
        # max_read_retries: 1

        # The interval, in seconds, in which reads on a mongos are retried. (default: 0)
        # read_retry_interval: 0

        # Timeout for SSL handshake. (default: 10)
        # ssl_timeout: 10

        # SSL options. Varies by Ruby version, returned as a hash.
        # Refer to the Ruby OpenSSL documentation for details.
        # ssl_options: {}

        # SSL verification mode. (default: true)
        # ssl_verify: true

        # Options for MongoDB driver logging. (default: false)
        # truncate_logs: false

        # Sets the server API version when connecting to MongoDB.
        # server_api:
        #   version: 1

        # When this flag is true, the driver will log all executed commands (including sensitive data) to the configured logger.
        # THIS OPTION SHOULD BE USED WITH CAUTION AS IT MAY LOG SENSITIVE DATA.
        # log_message: false

        # Whether to truncate long log lines. (default: true)
        # truncate_logs: true

  # Configure Mongoid-specific options. (optional)
  options:
    # Application name that is printed to the MongoDB logs upon establishing
    # a connection. Note that the name cannot exceed 128 bytes in length.
    app_name: CreatiaApp

    # Mark belongs_to associations as required by default, so that saving a
    # model with a missing belongs_to association will trigger a validation
    # error.
    belongs_to_required_by_default: true

    # Raise an exception when a field is redefined.
    duplicate_fields_exception: true

    # Raise an error when performing a #find and the document is not found.
    # (default: true)
    raise_not_found_error: false
    
    # Return stored times as UTC
    use_utc: false

test:
  clients:
    default:
      uri: <%= ENV['MONGODB_URI_TEST'] || 'mongodb://creatia_user:creatia_pass@localhost:27017/creatia_logs_test' %>
      options:
        connect: :direct
        read:
          mode: :primary
        max_pool_size: 5
        min_pool_size: 1
        server_selection_timeout: 5
        connect_timeout: 5
        socket_timeout: 5

production:
  clients:
    default:
      # 프로덕션에서는 MongoDB Atlas 사용
      uri: <%= ENV['MONGODB_URI_PRODUCTION'] || ENV['MONGODB_URI'] %>
      options:
        # The default write concern.
        write:
          w: 1
        
        # Change the default read preference. Valid options for mode are: :secondary,
        # :secondary_preferred, :primary, :primary_preferred, :nearest
        read:
          mode: :primary_preferred
        
        # The maximum number of connections in the connection pool.
        max_pool_size: 20
        
        # The minimum number of connections in the connection pool.
        min_pool_size: 5
        
        # The time to wait, in seconds, in the connection pool for a connection
        # to be checked in before timing out.
        wait_queue_timeout: 5
        
        # The time to wait to establish a connection before timing out, in seconds.
        connect_timeout: 10
        
        # The timeout in seconds for selecting a server for an operation.
        server_selection_timeout: 30
        
        # How long to wait for a response for each operation sent to the server.
        socket_timeout: 5
        
        # Compressors to use for wire protocol compression.
        compressors: ["zstd", "snappy", "zlib"]
        
        # The number of times to attempt a read operation before giving up.
        max_read_retries: 1
        
        # SSL verification mode.
        ssl_verify: true

  options:
    # Application name that is printed to the MongoDB logs.
    app_name: CreatiaApp_Production
    
    # Mark belongs_to associations as required by default.
    belongs_to_required_by_default: true
    
    # Raise an exception when a field is redefined.
    duplicate_fields_exception: true
    
    # Raise an error when performing a #find and the document is not found.
    raise_not_found_error: false